// List of Nigerian Universities (Federal, State, and Private)
export const NIGERIAN_UNIVERSITIES = [
  // Federal Universities
  "Abubakar Tafawa Balewa University, Bauchi",
  "Ahmadu Bello University, Zaria",
  "Alex Ekwueme Federal University, Ndufu-Alike",
  "Bayero University, Kano",
  "Federal University Gashua",
  "Federal University Gusau",
  "Federal University Birnin Kebbi",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University of Agriculture, Makurdi",
  "Federal University of Health Sciences, Otukpo",
  "Federal University of Petroleum Resources, Effurun",
  "Federal University of Technology, Akure",
  "Federal University of Technology, Minna",
  "Federal University of Technology, Owerri",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Michael Okpara University of Agriculture, Umudike",
  "Modibbo Adama University, Yola",
  "National Open University of Nigeria",
  "Nigerian Defence Academy, Kaduna",
  "Nnamdi Azikiwe University, Awka",
  "Obafemi Awolowo University, Ile-Ife",
  "University of Abuja",
  "University of Benin",
  "University of Calabar",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Nigeria, Nsukka",
  "University of Port Harcourt",
  "University of Uyo",
  "Usmanu Danfodiyo University, Sokoto",
  
  // State Universities
  "Abia State University, Uturu",
  "Adamawa State University, Mubi",
  "Adekunle Ajasin University, Akungba-Akoko",
  "Akwa Ibom State University",
  "Ambrose Alli University, Ekpoma",
  "Anambra State University",
  "Bauchi State University, Gadau",
  "Benue State University, Makurdi",
  "Borno State University, Maiduguri",
  "Chukwuemeka Odumegwu Ojukwu University",
  "Cross River University of Technology",
  "Delta State University, Abraka",
  "Ebonyi State University, Abakaliki",
  "Ekiti State University, Ado-Ekiti",
  "Enugu State University of Science and Technology",
  "Gombe State University",
  "Ibrahim Badamasi Babangida University, Lapai",
  "Ignatius Ajuru University of Education",
  "Imo State University, Owerri",
  "Kaduna State University",
  "Kano State University of Science and Technology",
  "Kebbi State University of Science and Technology",
  "Kogi State University, Anyigba",
  "Kwara State University, Malete",
  "Lagos State University, Ojo",
  "Ladoke Akintola University of Technology, Ogbomoso",
  "Nasarawa State University, Keffi",
  "Niger State University, Lapai",
  "Ogun State University",
  "Olabisi Onabanjo University, Ago-Iwoye",
  "Ondo State University of Science and Technology",
  "Osun State University, Osogbo",
  "Plateau State University, Bokkos",
  "Rivers State University",
  "Sokoto State University",
  "Tai Solarin University of Education",
  "Taraba State University, Jalingo",
  "Umaru Musa Yar'Adua University, Katsina",
  "Yobe State University, Damaturu",
  "Zamfara State University, Talata Mafara",
  
  // Private Universities
  "Achievers University, Owo",
  "Adeleke University, Ede",
  "Afe Babalola University, Ado-Ekiti",
  "African University of Science and Technology, Abuja",
  "Anchor University, Lagos",
  "Augustine University, Ilara-Epe",
  "Babcock University, Ilishan-Remo",
  "Baze University, Abuja",
  "Bells University of Technology, Ota",
  "Benson Idahosa University, Benin City",
  "Bowen University, Iwo",
  "Caleb University, Lagos",
  "Caritas University, Amorji-Nike",
  "CETEP City University, Lagos",
  "Chrisland University, Abeokuta",
  "Christopher University, Mowe",
  "Covenant University, Ota",
  "Crawford University, Igbesa",
  "Crescent University, Abeokuta",
  "Dominican University, Ibadan",
  "Edwin Clark University, Kiagbodo",
  "Elizade University, Ilara-Mokin",
  "Evangel University, Akaeze",
  "Fountain University, Osogbo",
  "Glorious Vision University, Ogwa",
  "Godfrey Okoye University, Enugu",
  "Gregory University, Uturu",
  "Hallmark University, Ijebu-Itele",
  "Hezekiah University, Umudi",
  "Igbinedion University, Okada",
  "Joseph Ayo Babalola University, Ikeji-Arakeji",
  "Kings University, Odeomu",
  "Kwararafa University, Wukari",
  "Landmark University, Omu-Aran",
  "Lead City University, Ibadan",
  "Madonna University, Okija",
  "McPherson University, Seriki-Sotayo",
  "Micheal & Cecilia Ibru University",
  "Mountain Top University, Ogun State",
  "Nile University of Nigeria, Abuja",
  "Novena University, Ogume",
  "Oduduwa University, Ipetumodu",
  "Pan-Atlantic University, Lagos",
  "Paul University, Awka",
  "Redeemer's University, Ede",
  "Renaissance University, Enugu",
  "Rhema University, Obeama-Asa",
  "Ritman University, Ikot Ekpene",
  "Salem University, Lokoja",
  "Samuel Adegboyega University, Ogwa",
  "Skyline University Nigeria, Kano",
  "Southwestern University, Oku-Owa",
  "Summit University, Offa",
  "Tansian University, Umunya",
  "Veritas University, Abuja",
  "Wellspring University, Evbuobanosa",
  "Wesley University, Ondo",
  "Western Delta University, Oghara",
  
  // Other
  "Other (Not Listed)",
].sort();

// Check if a university is a key partner (e.g., initial pivot partner)
export const isPartnerUniversity = (university: string): boolean => {
  return university.includes("Partner");
};
